name: http_io
repository: https://github.com/dart-lang/http_io
description: HTTP Client and Server APIs.
version: 3.10.0+2

environment:
  sdk: ">=3.10.0 <4.0.0"

workspace:
  - packages/async_helper
  - packages/expect

dependencies:
  meta: ^1.17.0

dev_dependencies:
  convert: ^3.1.2
  crypto: ^3.0.7
  lints: ^6.0.0
  path: ^1.9.1
  expect: any
